baseURL = 'https://parth-badgujar.github.io/'
languageCode = 'en-us'
title = "Parth's Blog"
theme = 'PaperMod'
[caches]
  [caches.images]
    dir = ':cacheDir/images'


[params]
math = true
ShowReadingTime = true


[params.assets]
  favicon = "favicon.ico"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 4

[[socialIcons]]
name = "github"
url = "https://github.com/clarelgibson"

[[socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/clarelgibson"


